// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApi.Models;

namespace ReactApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactApi.Models.Department", b =>
                {
                    b.Property<int>("DepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepId = 1,
                            DepName = "Department1"
                        },
                        new
                        {
                            DepId = 2,
                            DepName = "Department2"
                        },
                        new
                        {
                            DepId = 3,
                            DepName = "Department3"
                        });
                });

            modelBuilder.Entity("ReactApi.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("DepId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            DepId = 2,
                            Email = "employee1@gmail.com",
                            EmpName = "Employee1",
                            Salary = 11000
                        },
                        new
                        {
                            EmpId = 2,
                            DepId = 1,
                            Email = "employee2@gmail.com",
                            EmpName = "Employee2",
                            Salary = 22000
                        },
                        new
                        {
                            EmpId = 3,
                            DepId = 3,
                            Email = "employee3@gmail.com",
                            EmpName = "Employee3",
                            Salary = 33000
                        },
                        new
                        {
                            EmpId = 4,
                            DepId = 3,
                            Email = "employee4@gmail.com",
                            EmpName = "Employee4",
                            Salary = 44000
                        },
                        new
                        {
                            EmpId = 5,
                            DepId = 1,
                            Email = "employee5@gmail.com",
                            EmpName = "Employee5",
                            Salary = 55000
                        },
                        new
                        {
                            EmpId = 6,
                            DepId = 2,
                            Email = "employee6@gmail.com",
                            EmpName = "Employee6",
                            Salary = 66000
                        });
                });

            modelBuilder.Entity("ReactApi.Models.Employee", b =>
                {
                    b.HasOne("ReactApi.Models.Department", "Dep")
                        .WithMany()
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dep");
                });
#pragma warning restore 612, 618
        }
    }
}
